default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: patoinformatico
  host: localhost

development:
  <<: *default
  database: crazy4cats_development

test:
  <<: *default
  database: crazy4cats_test

production:
  <<: *default
  database: crazy4cats_production
  username: crazy4cats
  password: <%= ENV['CRAZY4CATS_DATABASE_PASSWORD'] %>
